export const vietnameseWords = [
  { origin: "Xin Chao", translation: "Hello" },
  { origin: "Tam Biet", translation: "Goodbye" },
  { origin: "Cam on", translation: "Thank you" },
  { origin: "Khong sao", translation: "No problem" },
  { origin: "Duoc roi", translation: "Okay" },
  { origin: "Ban be", translation: "Friends" },
  { origin: "Tinh yeu", translation: "Love" },
  { origin: "Chuc mung", translation: "Congratulations" },
  { origin: "Vui ve", translation: "Happy" },
  { origin: "That tuyet voi", translation: "Awesome" },
  { origin: "Tot nhat", translation: "Best" },
  { origin: "Khong can", translation: "Don't need" },
  { origin: "Hay di", translation: "Go ahead" },
  { origin: "Khong dong y", translation: "Disagree" },
  { origin: "Toi hieu", translation: "I understand" },
  { origin: "Noi chuyen", translation: "Chat" },
  { origin: "Di mua sam", translation: "Go shopping" },
  { origin: "Nguoi yeu", translation: "Boyfriend/girlfriend" },
  { origin: "Hoc tap", translation: "Study" },
  { origin: "Di choi", translation: "Go out" }
];

export const chineseWords = [
  { origin: "你好", translation: "hello" },
  { origin: "谢谢", translation: "thank you" },
  { origin: "对不起", translation: "sorry" },
  { origin: "没关系", translation: "it's okay" },
  { origin: "再见", translation: "goodbye" },
  { origin: "早上好", translation: "good morning" },
  { origin: "晚上好", translation: "good evening" },
  { origin: "我爱你", translation: "I love you" },
  { origin: "不客气", translation: "you're welcome" },
  { origin: "请问", translation: "excuse me" },
  { origin: "明天见", translation: "see you tomorrow" },
  { origin: "干杯", translation: "cheers" },
  { origin: "好的", translation: "okay" },
  { origin: "不好意思", translation: "excuse me" },
  { origin: "加油", translation: "come on" },
  { origin: "没事", translation: "it's okay" },
  { origin: "大家好", translation: "hello everyone" },
  { origin: "多谢", translation: "thanks a lot" },
  { origin: "不错", translation: "not bad" },
  { origin: "一起", translation: "together" },
];

export const japaneseWords = [
  { origin: "arigatou", translation: "thank you" },
  { origin: "gomen", translation: "sorry" },
  { origin: "kawaii", translation: "cute" },
  { origin: "sakura", translation: "cherry blossom" },
  { origin: "sensei", translation: "teacher" },
  { origin: "sumimasen", translation: "excuse me" },
  { origin: "mochi", translation: "rice cake" },
  { origin: "kudasai", translation: "please" },
  { origin: "manga", translation: "comic book" },
  { origin: "ramen", translation: "noodle soup" },
  { origin: "onsen", translation: "hot spring" },
  { origin: "konbanwa", translation: "good evening" },
  { origin: "arimasu", translation: "there is" },
  { origin: "imasu", translation: "there are" },
  { origin: "daisuki", translation: "I love you" },
  { origin: "itadakimasu", translation: "thank you for the meal" },
  { origin: "oyasumi", translation: "goodnight" },
  { origin: "konnichiwa", translation: "hello" },
  { origin: "ohayou", translation: "good morning" },
  { origin: "shinjiru", translation: "believe" }
];

export const bangladeshWords = [
  { origin: 'আসসালামু আলাইকুম', translation: 'Hello (Islamic greeting)' },
  { origin: 'কেমন আছো?', translation: 'How are you?' },
  { origin: 'আমি ভালো আছি, ধন্যবাদ', translation: 'I am fine, thank you' },
  { origin: 'আপনার নাম কি?', translation: 'What is your name?' },
  { origin: 'আমার নাম ...', translation: 'My name is ...' },
  { origin: 'কত বছর হল?', translation: 'How old are you?' },
  { origin: 'আমি ... বছর বয়সী', translation: 'I am ... years old' },
  { origin: 'দুঃখিত', translation: 'Sorry' },
  { origin: 'আমি বাংলা বলতে পারি না', translation: 'I can’t speak Bengali' },
  { origin: 'আমি ইংরেজীতে কথা বলতে পারি', translation: 'I can speak English' },
  { origin: 'বিদায়', translation: 'Goodbye' },
  { origin: 'ধন্যবাদ', translation: 'Thank you' },
  { origin: 'আপনি কী করেন?', translation: 'What do you do?' },
  { origin: 'আমি ছাত্র', translation: 'I am a student' },
  { origin: 'খাবার কি আছে?', translation: 'What is there to eat?' },
  { origin: 'আমার খুব ভালো লাগছে', translation: 'I am enjoying this very much' },
  { origin: 'আপনার কাছে কি কিছু আছে?', translation: 'Do you have anything?' },
  { origin: 'আমি বাসায় থাকি', translation: 'I live in a house' },
  { origin: 'কি সময়?', translation: 'What is the time?' },
  { origin: 'আমার কাছে কথা বলুন', translation: 'Talk to me' }
];


export const koreanWords = [
  { origin: '안녕하세요', translation: 'Hello' },
  { origin: '감사합니다', translation: 'Thank you' },
  { origin: '미안합니다', translation: 'I’m sorry' },
  { origin: '화이팅', translation: 'Let’s go!' },
  { origin: '잘 지내세요', translation: 'How are you?' },
  { origin: '여보세요', translation: 'Hello? (on the phone)' },
  { origin: '반갑습니다', translation: 'Nice to meet you' },
  { origin: '어떻게 지내세요?', translation: 'How are you?' },
  { origin: '고마워요', translation: 'Thank you' },
  { origin: '내일 봐요', translation: 'See you tomorrow' },
  { origin: '괜찮아요', translation: 'It’s okay' },
  { origin: '실례합니다', translation: 'Excuse me' },
  { origin: '잘 자요', translation: 'Goodnight' },
  { origin: '죄송합니다', translation: 'I’m sorry' },
  { origin: '화이팅!', translation: 'You can do it!' },
  { origin: '다시 한번 말해주세요', translation: 'Can you say that again?' },
  { origin: '저기요', translation: 'Excuse me (to get attention)' },
  { origin: '한국어 잘 못해요', translation: 'I don’t speak origin well' },
  { origin: '좋은 아침입니다', translation: 'Good morning' },
  { origin: '안녕히 가세요', translation: 'Goodbye (to someone leaving)'}
];
